/**
 * build-sidecar.mjs — compile the Node/Express backend into a single-file
 * executable ("pldl-server") for use as a Tauri sidecar.
 *
 * Pipeline: esbuild bundles server.js + lib/* into one CJS file, then Node's
 * built-in SEA injects that bundle into a self-contained `node` binary. No Node
 * install is needed on the end user's machine.
 *
 * IMPORTANT: the SEA base must be an OFFICIAL nodejs.org binary. Package-manager
 * builds (e.g. Homebrew) are tiny shared-lib launchers that lack the SEA fuse
 * sentinel and aren't self-contained, so we download the official binary that
 * matches the running Node version and inject into that.
 *
 * Usage: npm run build:sidecar   (output: build/pldl-server[.exe])
 */

import { build } from 'esbuild';
import { execFileSync } from 'node:child_process';
import { mkdirSync, copyFileSync, writeFileSync, chmodSync, rmSync, createWriteStream } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pipeline } from 'node:stream/promises';
import { Readable } from 'node:stream';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const buildDir = join(root, 'build');
const bundle = join(buildDir, 'pldl-server.js');
const seaConfig = join(buildDir, 'sea-config.json');
const blob = join(buildDir, 'sea-prep.blob');
const isWin = process.platform === 'win32';
const isMac = process.platform === 'darwin';
const out = join(buildDir, isWin ? 'pldl-server.exe' : 'pldl-server');
const FUSE = 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2';

function sh(cmd, args) {
  console.log(`  $ ${cmd} ${args.join(' ')}`);
  execFileSync(cmd, args, { stdio: 'inherit' });
}

async function downloadOfficialNode() {
  const v = process.version;                                  // e.g. v25.9.0
  const plat = isWin ? 'win' : (isMac ? 'darwin' : 'linux');
  const arch = process.arch;                                  // arm64 | x64
  const name = `node-${v}-${plat}-${arch}`;
  const archive = isWin ? `${name}.zip` : `${name}.tar.gz`;
  const url = `https://nodejs.org/dist/${v}/${archive}`;
  const archivePath = join(buildDir, archive);
  const extractDir = join(buildDir, 'nodebase');

  console.log(`• Downloading official Node base: ${url}`);
  const res = await fetch(url, { redirect: 'follow', signal: AbortSignal.timeout(180_000) });
  if (!res.ok) throw new Error(`Node download failed (${res.status}): ${url}`);
  await pipeline(Readable.fromWeb(res.body), createWriteStream(archivePath));

  mkdirSync(extractDir, { recursive: true });
  sh('tar', ['-xf', archivePath, '-C', extractDir]);          // bsdtar handles .tar.gz and .zip
  return isWin ? join(extractDir, name, 'node.exe') : join(extractDir, name, 'bin', 'node');
}

rmSync(buildDir, { recursive: true, force: true });
mkdirSync(buildDir, { recursive: true });

// 1. Bundle the whole server (server.js + lib/*) into one CJS file.
console.log('• Bundling with esbuild...');
await build({
  entryPoints: [join(root, 'server.js')],
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'cjs',
  outfile: bundle,
});

// 2. SEA config + blob (generated by the running node; same version as the base).
console.log('• Generating SEA blob...');
writeFileSync(seaConfig, JSON.stringify({
  main: bundle,
  output: blob,
  disableExperimentalSEAWarning: true,
}, null, 2));
sh(process.execPath, ['--experimental-sea-config', seaConfig]);

// 3. Official self-contained node binary as the injection base.
const base = await downloadOfficialNode();
copyFileSync(base, out);
chmodSync(out, 0o755);                                        // official tarball binaries are read-only

// 4. (macOS) strip the signature before injecting.
if (isMac) sh('codesign', ['--remove-signature', out]);

// 5. Inject the blob.
console.log('• Injecting SEA blob with postject...');
const postjectArgs = ['--yes', 'postject', out, 'NODE_SEA_BLOB', blob, '--sentinel-fuse', FUSE];
if (isMac) postjectArgs.push('--macho-segment-name', 'NODE_SEA');
sh('npx', postjectArgs);

// 6. (macOS) ad-hoc re-sign so dyld/Gatekeeper will load it.
if (isMac) sh('codesign', ['--sign', '-', out]);

console.log(`\n✓ Built ${out}`);
console.log('  Place it for Tauri with the Rust target-triple suffix, e.g.:');
console.log('    cp build/pldl-server "src-tauri/binaries/pldl-server-$(rustc -Vv | sed -n \'s/host: //p\')"');
